language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: MarcoFavorito
  password:
    secure: iCf+dwbqimx8tE5Nmh7bteZlRnOORS4tRdVisXp8lxoXcj1+WQcrBPIc2JqyKm2/N4uQudV8dHJ97eV0xgoELvAPnbe3sgxO+cibMB38+ooHVLLZ5G6Os314B9bL2ku5cGv6xkQJ7xzy6TYsXQopSMXdoG6QsH6PHuB+HkTiJ42aNtQ5pCpi05fezHzNIlAxsunlMUr6Oug4U5CPaa8s71ylLFMNM1TyoHyrNdZp/yuE1sRVGauoFQtVAE/cQnGsEhWWvwbXOe8YSWqAuDGogZmzmit9un7k1I31gGWCOd73FOyhd/wUnEiUk0L416hrvo8bSZ4zRShY4jZtdKMFa+yY+t+0Vc/jfMNP9t6yKDKQy4IbN3gXUytckhTfOFri+j6Xah6iriEdtdoO3IDQtdnH2FirSKjrCnjLYh279MiqswkwZUBC1Fib9ENKUBjzTWw0SjFQf6+fcjDaFKB+f+6syJaO7BE0bsMvf8Yghtpu8Y3zblk7Hjb+jEpR2totz/CYa3GLuw5OD3mzOtVQnn67oUpz8FCqX7IGLixETeu2LI3V0if5+KUrCe8ug7JXMp0up/sld+yyY5cw8bY+xn9PAfw9oR1QC5u/BKTAg0VVp+nw7rh3AaoPuHCGA5zQDQQQNdatlR4UJQiMdkJxv1pxSbQSLdpi+JCuIdChOoc=
  on:
    tags: true
    repo: MarcoFavorito/pythogic
    python: 3.6
